// <auto-generated />
using System;
using HaircutBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaircutBooking.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HaircutBooking.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HaircutBooking.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A standard haircut service.",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Basic Haircut",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A premium haircut service with additional styling.",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Deluxe Haircut",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional beard shaping and trimming",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Beard Trim",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Complete grooming package",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Haircut + Beard",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Special haircut for children with fun styling",
                            DurationMinutes = 25,
                            IsActive = true,
                            Name = "Kids Haircut",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Haircut service for senior citizens",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Senior Haircut",
                            Price = 17.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Modern fade style with precise blending",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Fade Haircut",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Short, even length buzz cut all over",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Buzz Cut",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Precise scissor-only haircut for natural look",
                            DurationMinutes = 40,
                            IsActive = true,
                            Name = "Scissor Cut",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Professional hair washing with conditioning treatment",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Hair Wash & Treatment",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Professional hair coloring service",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Hair Coloring",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Professional styling for special occasions",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Hair Styling",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Traditional straight razor shave with hot towels",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Traditional Shave",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Precise mustache shaping and trimming",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Mustache Trim",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Deep conditioning treatment for hair and scalp",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Hair & Scalp Treatment",
                            Price = 35.00m
                        });
                });

            modelBuilder.Entity("HaircutBooking.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HaircutBooking.Models.Appointment", b =>
                {
                    b.HasOne("HaircutBooking.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HaircutBooking.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
